//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace net.brotherus.game {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Configuration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SystemType[] systemsField;
        
        private Races racesField;
        
        private string currentGameFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SpaceSystem", IsNullable=false)]
        public SystemType[] Systems {
            get {
                return this.systemsField;
            }
            set {
                this.systemsField = value;
                this.RaisePropertyChanged("Systems");
            }
        }
        
        /// <remarks/>
        public Races Races {
            get {
                return this.racesField;
            }
            set {
                this.racesField = value;
                this.RaisePropertyChanged("Races");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrentGameFileName {
            get {
                return this.currentGameFileNameField;
            }
            set {
                this.currentGameFileNameField = value;
                this.RaisePropertyChanged("CurrentGameFileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlanetSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HomeSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RedSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuperNova))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AsteroidField))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IonStorm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nebula))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmptySystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetupTile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class SystemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Fleet fleetField;
        
        private int xField;
        
        private bool xFieldSpecified;
        
        private int yField;
        
        private bool yFieldSpecified;
        
        private string nameField;
        
        private string picFileNameField;
        
        private WormHoleID wormHoleField;
        
        private bool wormHoleFieldSpecified;
        
        /// <remarks/>
        public Fleet Fleet {
            get {
                return this.fleetField;
            }
            set {
                this.fleetField = value;
                this.RaisePropertyChanged("Fleet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
                this.RaisePropertyChanged("xSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
                this.RaisePropertyChanged("ySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string picFileName {
            get {
                return this.picFileNameField;
            }
            set {
                this.picFileNameField = value;
                this.RaisePropertyChanged("picFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WormHoleID wormHole {
            get {
                return this.wormHoleField;
            }
            set {
                this.wormHoleField = value;
                this.RaisePropertyChanged("wormHole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wormHoleSpecified {
            get {
                return this.wormHoleFieldSpecified;
            }
            set {
                this.wormHoleFieldSpecified = value;
                this.RaisePropertyChanged("wormHoleSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Fleet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RaceType ownerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RaceType owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    public enum RaceType {
        
        /// <remarks/>
        Hacan,
        
        /// <remarks/>
        JolNar,
        
        /// <remarks/>
        L1z1x,
        
        /// <remarks/>
        Letnev,
        
        /// <remarks/>
        Mentak,
        
        /// <remarks/>
        Muaat,
        
        /// <remarks/>
        Naalu,
        
        /// <remarks/>
        Norr,
        
        /// <remarks/>
        Saar,
        
        /// <remarks/>
        Sol,
        
        /// <remarks/>
        Winnu,
        
        /// <remarks/>
        Xxcha,
        
        /// <remarks/>
        Yin,
        
        /// <remarks/>
        Yssaril,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    public enum WormHoleID {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HomeSystem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlanetSystem : SystemType {
        
        private Planet[] planetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Planet")]
        public Planet[] Planet {
            get {
                return this.planetField;
            }
            set {
                this.planetField = value;
                this.RaisePropertyChanged("Planet");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Planet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int resourcesField;
        
        private int influenceField;
        
        private bool exhaustedField;
        
        private TechColor techSpecialityField;
        
        private bool techSpecialityFieldSpecified;
        
        private RaceType ownerField;
        
        private bool ownerFieldSpecified;
        
        public Planet() {
            this.exhaustedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
                this.RaisePropertyChanged("resources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int influence {
            get {
                return this.influenceField;
            }
            set {
                this.influenceField = value;
                this.RaisePropertyChanged("influence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool exhausted {
            get {
                return this.exhaustedField;
            }
            set {
                this.exhaustedField = value;
                this.RaisePropertyChanged("exhausted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TechColor techSpeciality {
            get {
                return this.techSpecialityField;
            }
            set {
                this.techSpecialityField = value;
                this.RaisePropertyChanged("techSpeciality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool techSpecialitySpecified {
            get {
                return this.techSpecialityFieldSpecified;
            }
            set {
                this.techSpecialityFieldSpecified = value;
                this.RaisePropertyChanged("techSpecialitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RaceType owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ownerSpecified {
            get {
                return this.ownerFieldSpecified;
            }
            set {
                this.ownerFieldSpecified = value;
                this.RaisePropertyChanged("ownerSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    public enum TechColor {
        
        /// <remarks/>
        Blue,
        
        /// <remarks/>
        Green,
        
        /// <remarks/>
        Red,
        
        /// <remarks/>
        Yellow,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HomeSystem : PlanetSystem {
        
        private RaceType raceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RaceType race {
            get {
                return this.raceField;
            }
            set {
                this.raceField = value;
                this.RaisePropertyChanged("race");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuperNova))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AsteroidField))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IonStorm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nebula))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class RedSystem : SystemType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuperNova : RedSystem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AsteroidField : RedSystem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IonStorm : RedSystem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Nebula : RedSystem {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmptySystem : SystemType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetupTile : SystemType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Races : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Race raceField;
        
        /// <remarks/>
        public Race Race {
            get {
                return this.raceField;
            }
            set {
                this.raceField = value;
                this.RaisePropertyChanged("Race");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Race : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private RaceType shortNameField;
        
        private bool shortNameFieldSpecified;
        
        private string ccPicFileField;
        
        private string flagPicFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RaceType shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("shortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shortNameSpecified {
            get {
                return this.shortNameFieldSpecified;
            }
            set {
                this.shortNameFieldSpecified = value;
                this.RaisePropertyChanged("shortNameSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ccPicFile {
            get {
                return this.ccPicFileField;
            }
            set {
                this.ccPicFileField = value;
                this.RaisePropertyChanged("ccPicFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flagPicFile {
            get {
                return this.flagPicFileField;
            }
            set {
                this.flagPicFileField = value;
                this.RaisePropertyChanged("flagPicFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Game : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SystemType[] mapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SpaceSystem", IsNullable=false)]
        public SystemType[] Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("Map");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Systems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SystemType[] spaceSystemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SpaceSystem")]
        public SystemType[] SpaceSystem {
            get {
                return this.spaceSystemField;
            }
            set {
                this.spaceSystemField = value;
                this.RaisePropertyChanged("SpaceSystem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
